name: thelook_lakehouse
version: "1.0.0"
config-version: 2

profile: thelook_trino

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  thelook_lakehouse:
    bronze:
      +schema: bronze
      +materialized: ephemeral
    silver:
      +schema: silver
      +materialized: incremental
      +incremental_strategy: delete+insert
    gold:
      +schema: gold
      +materialized: table
      +on_table_exists: drop
