version: "3.9"

services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tpcds-superset
    env_file:
      - .env
    ports:
      - "8088:8088"
    networks:
      - data_network

networks:
  data_network:
    external: true
    name: data_network
