name: thelook_lakehouse
version: "1.0.0"
config-version: 2

profile: thelook_trino

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  thelook_lakehouse:
    staging:
      +schema: staging
      +materialized: ephemeral
    intermediate:
      +schema: intermediate
      +materialized: incremental
      +incremental_strategy: delete+insert
    mart:
      +schema: mart
      +materialized: table
      +on_table_exists: drop
      dim:
        +schema: mart
        +materialized: table
        +on_table_exists: drop
      fact:
        +schema: mart
        +materialized: table
        +on_table_exists: drop
