FROM bitnamilegacy/spark:3.5.6

USER 0

RUN pip install --no-cache-dir pyarrow pandas fastavro confluent-kafka[avro]

RUN set -eux; \
    mkdir -p "${SPARK_HOME}/jars"; \
    curl -fSL -o "${SPARK_HOME}/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar" "https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar"; \
    curl -fSL -o "${SPARK_HOME}/jars/spark-token-provider-kafka-0-10_2.12-3.5.0.jar" "https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar"; \
    curl -fSL -o "${SPARK_HOME}/jars/kafka-clients-3.5.0.jar" "https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.0/kafka-clients-3.5.0.jar"; \
    curl -fSL -o "${SPARK_HOME}/jars/commons-pool2-2.12.0.jar" "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.12.0/commons-pool2-2.12.0.jar"; \
    curl -fSL -o "${SPARK_HOME}/jars/delta-spark_2.12-3.0.0.jar" "https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.0.0/delta-spark_2.12-3.0.0.jar"; \
    curl -fSL -o "${SPARK_HOME}/jars/hadoop-aws-3.3.4.jar" "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar"; \
    curl -fSL -o "${SPARK_HOME}/jars/aws-java-sdk-bundle-1.12.791.jar" "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.791/aws-java-sdk-bundle-1.12.791.jar"

COPY conf/spark-defaults.conf ${SPARK_HOME}/conf/spark-defaults.conf
COPY conf/hive-site.xml ${SPARK_HOME}/conf/hive-site.xml

RUN chown -R 1001:1001 ${SPARK_HOME}/conf

ENV SPARK_JARS_DIR="${SPARK_HOME}/jars"
ENV PYTHONPATH="/opt/spark/jobs:${PYTHONPATH}"

USER 1001
