services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tpcds-airflow
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ../dbt:/opt/airflow/dbt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - data_network
    restart: unless-stopped

networks:
  data_network:
    external: true
    name: data_network
